### ISSUE TITLE
flashing?

### ISSUE THREAD

**Issue by mmcghee18** [the-pudding/nba-carry#12]
not sure if this is intentional or a big deal, but the highlighted text flashes purple for a second on refresh before becoming green

https://user-images.githubusercontent.com/16782770/129388697-fbe45019-d1a5-4014-9da1-a2c509d0343e.mov

**Comment by russellgoldenberg** [comment]
i only see it go from purple (gray) to green once on load, which is happening when the stylesheet is applied i think. not a big deal really though.

**Comment by matthewfdaniels** [comment]
guessing this is a FOUC thing yea?
